// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Docker setup uses the POSTGRES_* environment variables
    // url: `postgresql://${process.env["POSTGRES_USER"]}:${process.env["POSTGRES_PASSWORD"]}@localhost:5432/${process.env["POSTGRES_DB"]}?schema=public`,

    // Prisma Cloud setup uses the environment variable DATABASE_URL
    url: process.env['DATABASE_URL'],
  },
});
